export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const CLEAR_SERVICE_FIELD = 'CLEAR_SERVICE_FIELD';
export const CANCEL_EDIT = 'CANCEL_EDIT';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
